// lib/models/pomodoro_record.dart

import 'package:hive/hive.dart';

// This line is generated by the build_runner
part 'pomodoro_record.g.dart';

@HiveType(typeId: 0)
class PomodoroRecord extends HiveObject {
  @HiveField(0)
  late DateTime date;

  @HiveField(1)
  late int crushedTomatoes;

  @HiveField(2)
  late int halfTomatoes;

  @HiveField(3)
  late int wholeTomatoes;
}